version: "3"

services:
  #service1 backend
  api:
    container_name: e-commerce-back-container
    env_file:
       - .env
    depends_on:
      - mongodb-service
      #chnage par path dockerhub img
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    #voila rihabbenhasso/e-commerce-back
    image: rihabbenhasso/e-commerce-back
    ports:
      - "3000:3000"
    command: ["sh", "-c" , "npm run seed:db hello@lebondeveloppeur.com admin123 && npm start"]
    environment:
      - MONGO_URI=mongodb://mongodb-user:mongodb-pass@mongodb-service:27017/db-ecommerce?authSource=admin
      - JWT_SECRET=I1eZOSzokm9OIz
 #service2 base de donnee 
  mongodb-service:
    container_name: mongodb-container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb-user
      MONGO_INITDB_ROOT_PASSWORD: mongodb-pass
      MONGO_INITDB_DATABASE: db-ecommerce
    ports:
      - "27017:27017"
  #service3 OPTIONNEL OUTPUT de comme SGBD
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb-service
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb-pass
      ME_CONFIG_MONGODB_URL: mongodb://mongodb-user:mongodb-pass@mongodb-service:27017/db-ecommerce?authSource=admin
      ME_CONFIG_BASICAUTH: false